admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    options:   {i18n_prefix: admin}

app:
    resource: "@AppBundle/Controller/"
    type:    annotation

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: app_homepage
        permanent: true
